version: "3.8"
services:
  app:
    build: .
    image: f-iii-binance-p2p-importer
    volumes:
      - ./input:/app/input
      - ./output:/app/output
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      - USERID=1000
      - GROUPID=1000
      - SMB_USER=${SMB_USER:-smbuser}
      - SMB_PASS=${SMB_PASS:-smppassword}
    ports:
      - "139:139"
      - "445:445"
    command: >
      sh -c "smbuser=\"${SMB_USER:-smbuser}\"; smppassword=\"${SMB_PASS:-smppassword}\"; exec /usr/bin/smbd -F -S -u \"$smbuser;$smppassword\" -s \"input;/mount/input;yes;no\""
    stdin_open: true
    tty: true
    volumes:
      - ./input:/mount/input
